version: '2'
services:
  filebeat:
    image: prima/filebeat:1.3.1
    container_name: filebeat
    restart: always
    network_mode: "bridge"
    extra_hosts:
      - "logstash:192.168.0.131"
    volumes:
      - ./conf/filebeat.yml:/filebeat.yml
      - ./registry:/etc/registry
      - /tmp:/tmp
      - /Users/nhsoft/work/pintuan-dashboard/log:/dashboard
