version: '2'
services:
  logstash:
    image: logstash:2.4.1
    container_name: logstash
    restart: always
    network_mode: "bridge"
    ports:
      - "5044:5044"
      - "8080:8080"
    volumes:
      - ./conf:/config-dir
      - ./patterns:/opt/logstash/patterns
      # - /Users/nhsoft/work/pintuan-dashboard/log:/dashboard
    external_links:
      - elasticsearch:elasticsearch
    command: logstash -f /config-dir
